### ISSUE TITLE
Close Jedis connection after set or get

### ISSUE THREAD

**Issue by thienit5** [RedisLabs/JReJSON#4]
I don't know why JReJSON always close Jedis connection after action set or get?
So i can not use jedis conn any more when i use JedisPool

**Comment by itamarhaber** [comment]
I share you puzzlement and would be glad to accept a pull request that removes the offending `conn.close();` lines from the client's methods.

**Comment by gkorland** [comment]
JReJSON 1.1.0 is using Jedis Pool and doesn't require a connection
